docs: add the contributing guides to docs
s3gw-tech/s3gw pull request #279
Opened 2022-12-15 14:44 UTC by jhmarina

Signed-off-by: Jesus Herman-Marina <jherman@suse.com>

# Describe your changes

This PR implements a mkdocs plugin that renders a page taking content from another page. In this case it's injecting the content from `CONTRIBUTING.md `into` docs/contributing.md`

## Issue ticket number and link

## Checklist before requesting a review

- [x] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.
- [ ] CHANGELOG.md has been updated should there be relevant changes in this PR.

2022-12-16 14:04 UTC, m-ildefons requested changes
Two small nits, but otherwise it looks good to me. Nicely done.

2022-12-16 14:04 UTC, m-ildefons commented on CONTRIBUTING.md
> +
Superfluous empty line. In a code block this may result in weird formatting.

2022-12-16 14:04 UTC, m-ildefons commented on CONTRIBUTING.md
> +
Same again

2022-12-16 15:27 UTC, giubacc reviewed
with Moritz notes, LGTM

2022-12-16 18:36 UTC, jecluis reviewed
lgtm once @m-ildefons 's comments have been addressed.

2022-12-19 11:57 UTC, m-ildefons approved these changes
LGTM

2022-12-19 12:39 UTC, merged