Update 0007-release-process.md - Adding testing link
s3gw-tech/s3gw pull request #706
Opened 2023-09-11 15:25 UTC by vmoutoussamy

# Describe your changes

Adding link to https://github.com/aquarist-labs/s3gw/blob/main/docs/testing.md in the testing section of the release process document.

## Issue ticket number and link

## Checklist before requesting a review

- [ ] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.
- [ ] CHANGELOG.md has been updated should there be relevant changes in this PR.

2023-09-20 10:53 UTC, jecluis requested changes

2023-09-20 10:53 UTC, jecluis commented on docs/decisions/0007-release-process.md
> +The list below need to be expanded in the future.
s/need/needs/

2023-09-20 15:21 UTC, jecluis commented
@vmoutoussamy please squash the two commits into one. After that I think this is fine to merge.

2023-09-29 09:55 UTC, jecluis commented
@vmoutoussamy commit needs to be signed.

2023-10-10 15:16 UTC, vmoutoussamy commented
Closing this as it's not really clean and I didn't use a branch in my fork for the PR

2023-10-10 15:16 UTC, closed without merging