Dockerfile: fix sqlite version to 3.43.1
s3gw-tech/s3gw pull request #729
Opened 2023-09-28 11:20 UTC by jecluis

To be merged after @tserong updates the  packages in https://build.opensuse.org/project/show/filesystems:ceph:s3gw and adds the newest sqlite3 3.43.1 version.

Fixes: aquarist-labs/s3gw#725

Signed-off-by: Joao Eduardo Luis \<joao@suse.com>

2023-09-29 04:06 UTC, tserong approved these changes
LGTM, but probably also wants to be done in tools/build/Dockerfile.build-radosgw and tools/build/Dockerfile.s3gw (although the latter should arguably be ultimately removed in favour of the top-level Dockerfile, but that can be done separately - see https://github.com/aquarist-labs/s3gw/issues/731)

2023-09-29 08:28 UTC, jecluis commented
Yeah, I think doing it as part of #731 makes sense :)

2023-09-29 09:28 UTC, tserong requested changes
I've got 3.43.1 into filesystems:ceph:s3gw now, tried a build, and we need one more little tweak here:

```diff
diff --git a/Dockerfile b/Dockerfile
index 5ef048b..1fadc39 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -5,7 +5,7 @@ RUN zypper ar \
   s3gw-deps \
  && zypper --gpg-auto-import-keys ref
 
-RUN zypper -n install \
+RUN zypper -n install --allow-vendor-change \
   libblkid1 \
   libexpat1 \
   libtcmalloc4 \
```

The problem is that the base image (opensuse/leap:15.4) already has libsqlite3-0-3.39.3-150000.3.20.1.x86_64 installed, so trying to install sqlite-devel=3.43.1 triggers this rotten thing:

```
156.6 Resolving package dependencies...
156.7 
156.7 Problem: the to be installed sqlite3-devel-3.43.1-lp154.322.1.x86_64 requires 'libsqlite3-0 = 3.43.1', but this requirement cannot be provided
156.7   not installable providers: libsqlite3-0-3.43.1-lp154.322.1.x86_64[s3gw-deps]
156.7  Solution 1: install libsqlite3-0-3.43.1-lp154.322.1.x86_64 from vendor obs://build.opensuse.org/filesystems
156.7   replacing libsqlite3-0-3.39.3-150000.3.20.1.x86_64 from vendor SUSE LLC <https://www.suse.com/>
156.7  Solution 2: do not ask to install a solvable providing sqlite-devel = 3.43.1
156.7  Solution 3: break sqlite3-devel-3.43.1-lp154.322.1.x86_64 by ignoring some of its dependencies
156.7 
156.7 Choose from above solutions by number or cancel [1/2/3/c/d/?] (c): c
```

2023-09-29 09:37 UTC, tserong commented
Wait a minute, it doesn't quite work even with that change. Stay tuned...

2023-09-29 09:49 UTC, tserong commented
...uh, the previous suggested tweak was in the wrong place >facepalm<. You actually want this one:

```
diff --git a/Dockerfile b/Dockerfile
index 5ef048b..491cc0b 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -43,7 +43,7 @@ ENV SRC_CEPH_DIR="${SRC_CEPH_DIR:-"./ceph"}"
 ENV ENABLE_GIT_VERSION=OFF
 
 # Add OBS repository for additional dependencies necessary on Leap 15.4
-RUN zypper -n install --no-recommends \
+RUN zypper -n install --no-recommends --allow-vendor-change \
       'cmake>3.5' \
       'fmt-devel>=6.2.1' \
       'gperftools-devel>=2.4' \
```

(Just waiting for a build to complete now, but I got past the install step with the above patch).

2023-09-29 11:00 UTC, tserong commented
Nope, that's not it either. The above works fine to get the right version of sqlite-devel installed when _building_ s3gw, but the container that s3gw _runs_ in still has version 3.39.3.

This is rapidly turning into a textbook example of why:
a) reviewers should always test dependency changes before giving them the OK
-- and --
b) one should never do reviews on a Friday night.

2023-09-29 12:39 UTC, tserong commented
Alright, _this_ does it:

```diff
diff --git a/Dockerfile b/Dockerfile
index 5ef048b..c1b9c19 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -6,6 +6,7 @@ RUN zypper ar \
  && zypper --gpg-auto-import-keys ref
 
 RUN zypper -n install \
+  libsqlite3-0=3.43.1 \
   libblkid1 \
   libexpat1 \
   libtcmalloc4 \
```

That's installing the desired version of libsqlite3-0  in s3gw-base, which is used by all the other containers. When buildenv is created, it pulls in the sqlite-devel version which matches the already installed libsqlite3-0. Apparently there's no need for `--allow-vendor-change` when doing it this way.

2023-10-03 03:14 UTC, tserong approved these changes

2023-10-04 05:53 UTC, merged