docs/decisions: Add severity labels ADR
s3gw-tech/s3gw pull request #755
Opened 2023-10-12 06:48 UTC by vmoutoussamy

# Describe your changes
Adding the file s3gw/docs/decisions/0015-severity-labels.md, for discussing the decision to use a new set of labels for severity.

## Issue ticket number and link

## Checklist before requesting a review

- [ ] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.
- [ ] CHANGELOG.md has been updated should there be relevant changes in this PR.

2023-10-12 06:53 UTC, jecluis commented
@vmoutoussamy commit is missing the DCO

I'd suggest running a `git commit --amend -S` and adding the DCO manually to the commit message.

2023-10-12 06:55 UTC, jecluis commented
@vmoutoussamy also, when amending the commit, please add the subsystem where this change is happening to the commit title.

Like, `docs/decisions: add severity labels ADR`

2023-10-12 07:08 UTC, jecluis requested changes

2023-10-12 07:08 UTC, jecluis commented on docs/decisions/0015-severity-labels.md
> +meeting which happened once every 4 weeks in our Release Cycle.
`which happened once every 4 weeks` -> `which happens once every Release Cycle`

Given that meeting is highly dependent on release cycle length, and said length has been changed around quite a bit, I think it makes sense to just not specify the length of the cycle here. In a sense, that is irrelevant for the meeting.

2023-10-12 07:08 UTC, jecluis commented on docs/decisions/0015-severity-labels.md
> +## Requierements
Typo. Should be `Requirements`.

2023-10-12 07:08 UTC, jecluis commented on docs/decisions/0015-severity-labels.md
> +- should be adaptable to other Rancher projects,
Either drop the commas, or ensure that the last item is a period instead of a comma. I'd go with the former.

2023-10-12 07:08 UTC, jecluis commented on docs/decisions/0015-severity-labels.md
> +## Definitions
This is not a section about definitions.

I'd rename it to `## Considered Alternatives`, and then make the `s3gw proposal` below a `## Outcome` or something.

2023-10-12 07:08 UTC, jecluis commented on docs/decisions/0015-severity-labels.md
> +### s3gw proposal
Maybe make this an `## Outcome`.

2023-10-12 07:08 UTC, jecluis commented on docs/decisions/0015-severity-labels.md
> +Function working but has a minor issue (a minor incident with low impact)
Please make this consistent with the other lists.

The description should be a bullet point itself, like the other two lists below. Or change the other lists to be like this one.

2023-10-12 07:08 UTC, jecluis commented on docs/decisions/0015-severity-labels.md
> +  - (Documentation) contains stylistic or formatting issues, but functionality is not hindered.
Drop the periods on each list item, make it consistent with other lists in the document.

2023-10-12 07:08 UTC, jecluis commented on docs/decisions/0015-severity-labels.md
> +  - Issue that can be viewed as trivial (e.g. cosmetic, UI, easily documented).
Drop the periods on each list item, make it consistent with other lists in the document.

2023-10-12 11:36 UTC, votdev requested changes, later dismissed

2023-10-12 11:36 UTC, votdev commented on docs/decisions/0015-severity-labels.md
> +This is not ideal as an issue can be leftover for weeks before before it's discussed during the
```suggestion
This is not ideal as an issue can be leftover for weeks before it's discussed during the
```

2023-10-12 11:36 UTC, votdev commented on docs/decisions/0015-severity-labels.md
> +Engineers. We would like to introduce a new type of Labels: Severity.
```suggestion
Engineers, we would like to introduce a new type of Labels: Severity.
```

2023-10-12 11:36 UTC, votdev commented on docs/decisions/0015-severity-labels.md
> +cannot be changed without discussing it with Joao or Vincent.
```suggestion
cannot be changed without discussing it with team lead.
```
or anything else.

2023-10-12 12:00 UTC, jecluis commented on docs/decisions/0015-severity-labels.md
> +cannot be changed without discussing it with Joao or Vincent.
during the call this morning, I think the consensus was "without discussing it with relevant stakeholders".

2023-10-12 12:04 UTC, tserong commented on docs/decisions/0015-severity-labels.md
> +  - Issue that can be viewed as trivial (e.g. cosmetic, UI, easily documented).
```suggestion
- severity/trivial
  - Issue that can be viewed as minor (e.g. cosmetic, UI, easily documented).
```

2023-10-12 16:30 UTC, jecluis commented
@vmoutoussamy you'll need to do a `git commit --amend` and clean up that commit message.

2023-10-13 07:05 UTC, jecluis requested changes

2023-10-13 07:05 UTC, jecluis commented on docs/decisions/0015-severity-labels.md
File name will need to be changed. Decision ID 0015 has been consumed by another pull request.

2023-10-13 07:08 UTC, jecluis commented on docs/decisions/0015-severity-labels.md
I suggest using 0019 to avoid conflicting with other in-flight pull requests

2023-10-26 06:22 UTC, jecluis commented
@vmoutoussamy right now your commit message looks like this:

```
[docs/decisions: Add severity labels ADR](https://github.com/aquarist-labs/s3gw/pull/755/commits/2d917136f54ede32a38feb08f1076f3b2cc884e2)

Signed-off-by: Vincent Moutoussamy <vmoutoussamy@suse.com>

Update docs/decisions/0015-severity-labels.md

Co-authored-by: Volker Theile <votdev@gmx.de>
Signed-off-by: Vincent Moutoussamy <vmoutoussamy@suse.com>

Update docs/decisions/0015-severity-labels.md

Co-authored-by: Volker Theile <votdev@gmx.de>
Signed-off-by: Vincent Moutoussamy <vmoutoussamy@suse.com>

Update docs/decisions/0015-severity-labels.md

Co-authored-by: Tim Serong <tserong@suse.com>
Signed-off-by: Vincent Moutoussamy <vmoutoussamy@suse.com>

Applying comments' suggestion

Signed-off-by: Vincent Moutoussamy <vmoutoussamy@suse.com>

Stakeholders need to be involved for setting priority

Signed-off-by: Vincent Moutoussamy <vmoutoussamy@suse.com>

Decision ID 0019 to avoid conflicts

Signed-off-by: Vincent Moutoussamy <vmoutoussamy@suse.com>

Fixing Lint check

Signed-off-by: Vincent Moutoussamy <vmoutoussamy@suse.com>

Fixing typo

Signed-off-by: Vincent Moutoussamy <vmoutoussamy@suse.com>

Fixing typos

Signed-off-by: Vincent Moutoussamy <vmoutoussamy@suse.com>

Following Markdownlint rules

Signed-off-by: Vincent Moutoussamy <vmoutoussamy@suse.com>
```

This is a result of all the squash/fixup you did on the different patches. We don't want this messy message, we want something lean and simple.

I would suggest you run a `git commit --amend -S` on that branch, adjust the message, and force push the resulting commit to the branch. Ping me when you've done this so we can merge this work.

2023-11-13 08:41 UTC, jecluis commented
@vmoutoussamy ping

2023-11-13 09:30 UTC, jecluis approved these changes

2023-11-13 09:31 UTC, merged