tools: script to run s3test with local binaries
s3gw-tech/s3gw pull request #794
Opened 2023-11-03 15:04 UTC by 0xavi0

This script tries to wrap different calls to `s3tr` in order to run `s3tests` against local radosgw builds.

There are 2 possible modes:
* Run all tests and the final analysis
* Run a single test and the the s3test output

The script needs the user to provide the location of radosgw using the `CEPH_DIR` environment variable.

Once that is provided it uses the `CEPH_BUILD_DIR` variable calculated as `CEPH_DIR/build`, but the user can also pass his/her own `CEPH_BUILD_DIR` if the default does not fit his/her environment.

Examples:
```bash
# RUNS ALL S3TESTS AND ANALYSIS
CEPH_DIR=/home/user/dev/ceph ./run_local_build_s3test.sh

# RUNS ONLY test_object_copy_to_itself S3TEST
CEPH_DIR=/home/user/dev/ceph ./run_local_build_s3test.sh test_object_copy_to_itself

# RUNS ALL S3TESTS, CEPH_BUILD_DIR is different to CEPH_DIR/build
export CEPH_DIR=/home/user/dev/ceph
export CEPH_BUILD_DIR=/home/user/dev/ceph/build_clang
./run_local_build_s3test.sh
```

- [x] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.
- [ ] CHANGELOG.md has been updated should there be relevant changes in this PR.

2023-11-03 15:48 UTC, giubacc commented
Amazing! tested, it works pretty well.
To me is good but better Marcel has a look.

2023-11-03 16:45 UTC, giubacc approved these changes, later dismissed

2023-11-13 08:39 UTC, jecluis commented
@irq0 quick look?

2023-11-13 13:23 UTC, irq0 requested changes
Please shellcheck, there are couple of quoting errors

2023-11-13 13:24 UTC, irq0 commented
It's high time that we get shellcheck into CI. Started a PR https://github.com/aquarist-labs/s3gw/pull/797 - maybe rebase?

2023-11-14 07:47 UTC, jecluis reviewed
> Examples:
> 
> ```shell
> # RUNS ALL S3TESTS AND ANALYSIS
> CEPH_DIR=/home/user/dev/ceph ./run_local_build_s3test.sh
> 
> # RUNS ONLY test_object_copy_to_itself S3TEST
> CEPH_DIR=/home/user/dev/ceph ./run_local_build_s3test.sh test_object_copy_to_itself
> 
> # RUNS ALL S3TESTS, CEPH_BUILD_DIR is different to CEPH_DIR/build
> export CEPH_DIR=/home/user/dev/ceph
> export CEPH_BUILD_DIR=/home/user/dev/ceph/build_clang
> ./run_local_build_s3test.sh
> ```

Can we add this as an example `usage()` to the script? It might help us understand what we need to provide when using it.

2023-11-16 07:35 UTC, 0xavi0 commented
> Can we add this as an example `usage()` to the script? It might help us understand what we need to provide when using it.

done

2023-11-16 07:43 UTC, jecluis approved these changes

2023-11-16 10:01 UTC, irq0 approved these changes

2023-11-16 11:26 UTC, merged